name: download

on:
  workflow_dispatch:

jobs:
  download:
    name: download image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      IMAGE: "kubeagi/core-library-cli:v0.0.1-20240308-18ea8aa"
    steps:
      - name: docker save
        run: |
          docker pull ${{ env.IMAGE }}
          docker save ${{ env.IMAGE }} > /tmp/image.tar.gz
      - name: Upload images
        uses: actions/upload-artifact@v3
        with:
          name: "image.tar.gz"
          path: "/tmp/image.tar.gz"
